/*!!!!!!! ATTENTON !!!!!!!
file autogenerated by grl.rb script. Do not change it
!!!!!!!!!!!!!!!!!!!!!!!!*/
package ru.catAndBall.view.assets {

	public final class AssetList {

		public static const Footer_bank:String = 'Footer/bank';
		public static const Footer_inventar:String = 'Footer/inventar';
		public static const Footer_pannel_pattern:String = 'Footer/pannel_pattern';
		public static const Footer_settings:String = 'Footer/settings';
		public static const Panel_components_bg_for_components:String = 'Panel_components/bg_for_components';
		public static const Panel_components_components_level_bg:String = 'Panel_components/components_level_bg';
		public static const Preloader_band_experience_green:String = 'Preloader/band_experience_green';
		public static const Preloader_cat:String = 'Preloader/cat';
		public static const Preloader_green_button:String = 'Preloader/green_button';
		public static const Preloader_green_button_on:String = 'Preloader/green_button_on';
		public static const Room_chest:String = 'Room/chest';
		public static const Room_collect_exp_icon:String = 'Room/collect_exp_icon';
		public static const Room_vhod_pole_klubki:String = 'Room/vhod_pole_klubki';
		public static const Strip_moves_ball_for_strip:String = 'Strip_moves/ball_for_strip';
		public static const Strip_moves_line_for_strip:String = 'Strip_moves/line_for_strip';
		public static const Strip_moves_strip_moves:String = 'Strip_moves/strip_moves';
		public static const Tools_name_tools_background:String = 'Tools/name_tools_background';
		public static const Tools_spitsbl:String = 'Tools/spitsbl';
		public static const Tools_tool_background_1:String = 'Tools/tool_background_1';
		public static const Tools_tool_background_2:String = 'Tools/tool_background_2';
		public static const ToolsOption_minus:String = 'ToolsOption/minus';
		public static const back:String = 'back';
		public static const connection_line_elements:String = 'connection_line_elements';
		public static const fields_balls_bg2:String = 'fields/balls/bg2';
		public static const fields_balls_bg3:String = 'fields/balls/bg3';
		public static const fields_balls_ebge_fieldballs:String = 'fields/balls/ebge_fieldballs';
		public static const fields_balls_object_balls_screenFieldBalls_toyPurple:String = 'fields/balls/object_balls/screenFieldBalls_toyPurple';
		public static const fields_carpet_tangle_for_bg:String = 'fields/carpet/tangle_for_bg';
		public static const fields_carpet_tangle_for_bg_down:String = 'fields/carpet/tangle_for_bg_down';
		public static const fields_window_object_window_gold_leaf:String = 'fields/window/object_window/gold_leaf';
		public static const header_band_experience_green:String = 'header/band_experience_green';
		public static const header_header_lvlIcon:String = 'header/header_lvlIcon';
		public static const header_pannel_pattern:String = 'header/pannel_pattern';
		public static const hint_angle:String = 'hint/angle';
		public static const hint_clock_icon:String = 'hint/clock_icon';
		public static const hint_hint_bg:String = 'hint/hint_bg';
		public static const hint_lvl_icon:String = 'hint/lvl_icon';
		public static const inventory_activ:String = 'inventory/activ';
		public static const inventory_pasiv:String = 'inventory/pasiv';
		public static const melody:String = 'melody';
		public static const panel_tools_background:String = 'panel_tools/background';
		public static const panel_tools_bg_pod_ikonki:String = 'panel_tools/bg_pod_ikonki';
		public static const panel_tools_kontener:String = 'panel_tools/kontener';
		public static const panel_tools_spitsbl:String = 'panel_tools/spitsbl';
		public static const panel_tools_strelka:String = 'panel_tools/strelka';
		public static const panel_tools_tools_footer_icon:String = 'panel_tools/tools_footer_icon';
		public static const repeat:String = 'repeat';
		public static const settings:String = 'settings';
		public static const Footer_button:String = 'Footer/button';
		public static const Room_carpet:String = 'Room/carpet';
		public static const Room_cat_house_lvl1:String = 'Room/cat_house_lvl1';
		public static const Room_regiment1Close:String = 'Room/regiment1Close';
		public static const Room_regiment2Close:String = 'Room/regiment2Close';
		public static const Room_window:String = 'Room/window';
		public static const Strip_moves_cat_for_strip:String = 'Strip_moves/cat_for_strip';
		public static const Tools_name_tools_active:String = 'Tools/name_tools_active';
		public static const Tools_name_tools_passive:String = 'Tools/name_tools_passive';
		public static const Tools_name_tools_unavailable:String = 'Tools/name_tools_unavailable';
		public static const ToolsOption_button:String = 'ToolsOption/button';
		public static const ToolsOption_close:String = 'ToolsOption/close';
		public static const button:String = 'button';
		public static const button_off:String = 'button_off';
		public static const button_on:String = 'button_on';
		public static const close:String = 'close';
		public static const fields_balls_component_screenFieldBalls_socksIcon:String = 'fields/balls/component/screenFieldBalls_socksIcon';
		public static const fields_carpet_bg2:String = 'fields/carpet/bg2';
		public static const fields_carpet_bg3:String = 'fields/carpet/bg3';
		public static const fields_window_bg1:String = 'fields/window/bg1';
		public static const fields_window_bg2:String = 'fields/window/bg2';
		public static const fields_window_bg3:String = 'fields/window/bg3';
		public static const fields_window_component_screenFieldCWindow_paintredIcon:String = 'fields/window/component/screenFieldCWindow_paintredIcon';
		public static const fields_window_component_screenFieldCWindow_ragsIcon:String = 'fields/window/component/screenFieldCWindow_ragsIcon';
		public static const fields_window_object_window_rabbit:String = 'fields/window/object_window/rabbit';
		public static const header_catmoneyIcon:String = 'header/catmoneyIcon';
		public static const header_header_mouseIcon:String = 'header/header_mouseIcon';
		public static const inventory_button:String = 'inventory/button';
		public static const inventory_close:String = 'inventory/close';
		public static const inventory_fon_pod_ikonki:String = 'inventory/fon_pod_ikonki';
		public static const inventory_grey_icon_coffe_shadow:String = 'inventory/grey_icon/coffe_shadow';
		public static const inventory_grey_icon_katushka_shadow:String = 'inventory/grey_icon/katushka_shadow';
		public static const inventory_grey_icon_konservbl_shadow:String = 'inventory/grey_icon/konservbl_shadow';
		public static const inventory_grey_icon_konteiner_shadow:String = 'inventory/grey_icon/konteiner_shadow';
		public static const inventory_grey_icon_paint_shadow:String = 'inventory/grey_icon/paint_shadow';
		public static const inventory_grey_icon_venik_shadow:String = 'inventory/grey_icon/venik_shadow';
		public static const inventory_shcatulka:String = 'inventory/shcatulka';
		public static const panel_tools_coffee:String = 'panel_tools/coffee';
		public static const pause:String = 'pause';
		public static const start_windows_X:String = 'start_windows/X';
		public static const start_windows_button:String = 'start_windows/button';
		public static const start_windows_carpet_icon:String = 'start_windows/carpet_icon';
		public static const volume:String = 'volume';
		public static const Footer_home:String = 'Footer/home';
		public static const Footer_mouse_worker:String = 'Footer/mouse_worker';
		public static const Panel_components_milk1:String = 'Panel_components/milk1';
		public static const Panel_components_milk2:String = 'Panel_components/milk2';
		public static const Preloader_band_experience_stroke:String = 'Preloader/band_experience_stroke';
		public static const Room_cat:String = 'Room/cat';
		public static const Room_regiment1Open:String = 'Room/regiment1Open';
		public static const Room_regiment2Open:String = 'Room/regiment2Open';
		public static const Room_regiment3Close:String = 'Room/regiment3Close';
		public static const Room_regiment3Open:String = 'Room/regiment3Open';
		public static const Room_shirma_stroitelstvo:String = 'Room/shirma_stroitelstvo';
		public static const Room_tangles:String = 'Room/tangles';
		public static const Room_vhod_pole_kover:String = 'Room/vhod_pole_kover';
		public static const Room_vhod_pole_okno:String = 'Room/vhod_pole_okno';
		public static const Tools_amount_components_off:String = 'Tools/amount_components_off';
		public static const Tools_amount_components_on:String = 'Tools/amount_components_on';
		public static const Tools_button_buy:String = 'Tools/button_buy';
		public static const Tools_tool_icon_background:String = 'Tools/tool_icon_background';
		public static const ToolsOption_amount_components_off:String = 'ToolsOption/amount_components_off';
		public static const ToolsOption_amount_components_on:String = 'ToolsOption/amount_components_on';
		public static const ToolsOption_bg:String = 'ToolsOption/bg';
		public static const ToolsOption_button_buy:String = 'ToolsOption/button_buy';
		public static const ToolsOption_button_buy_on:String = 'ToolsOption/button_buy_on';
		public static const ToolsOption_plus:String = 'ToolsOption/plus';
		public static const fields_balls_bg1:String = 'fields/balls/bg1';
		public static const fields_balls_component_screenFieldBalls_ballsIconDisabled:String = 'fields/balls/component/screenFieldBalls_ballsIconDisabled';
		public static const fields_balls_component_screenFieldBalls_socksIconDisabled:String = 'fields/balls/component/screenFieldBalls_socksIconDisabled';
		public static const fields_balls_component_screenFieldBalls_sweaterIcon:String = 'fields/balls/component/screenFieldBalls_sweaterIcon';
		public static const fields_balls_component_screenFieldBalls_toysIcon:String = 'fields/balls/component/screenFieldBalls_toysIcon';
		public static const fields_balls_component_screenFieldBalls_toysIconDisabled:String = 'fields/balls/component/screenFieldBalls_toysIconDisabled';
		public static const fields_balls_object_balls_frog:String = 'fields/balls/object_balls/frog';
		public static const fields_balls_object_balls_screenFieldBalls_ballBlue:String = 'fields/balls/object_balls/screenFieldBalls_ballBlue';
		public static const fields_balls_object_balls_screenFieldBalls_ballGold:String = 'fields/balls/object_balls/screenFieldBalls_ballGold';
		public static const fields_balls_object_balls_screenFieldBalls_ballRed:String = 'fields/balls/object_balls/screenFieldBalls_ballRed';
		public static const fields_balls_object_balls_screenFieldBalls_granny:String = 'fields/balls/object_balls/screenFieldBalls_granny';
		public static const fields_balls_object_balls_screenFieldBalls_sweaterBlue:String = 'fields/balls/object_balls/screenFieldBalls_sweaterBlue';
		public static const fields_balls_object_balls_screenFieldBalls_sweaterPurple:String = 'fields/balls/object_balls/screenFieldBalls_sweaterPurple';
		public static const fields_balls_object_balls_screenFieldBalls_sweaterRed:String = 'fields/balls/object_balls/screenFieldBalls_sweaterRed';
		public static const fields_balls_object_balls_screenFieldBalls_sweaterWhite:String = 'fields/balls/object_balls/screenFieldBalls_sweaterWhite';
		public static const fields_balls_object_balls_screenFieldBalls_toyWhite:String = 'fields/balls/object_balls/screenFieldBalls_toyWhite';
		public static const fields_balls_object_balls_screenFieldBalls_wolf:String = 'fields/balls/object_balls/screenFieldBalls_wolf';
		public static const fields_balls_object_balls_socks:String = 'fields/balls/object_balls/socks';
		public static const fields_carpet_bg1:String = 'fields/carpet/bg1';
		public static const fields_carpet_components_screenFieldCarpet_cannedIcon:String = 'fields/carpet/components/screenFieldCarpet_cannedIcon';
		public static const fields_carpet_components_screenFieldCarpet_cannedIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_cannedIconDisabled';
		public static const fields_carpet_components_screenFieldCarpet_sausageIcon:String = 'fields/carpet/components/screenFieldCarpet_sausageIcon';
		public static const fields_carpet_components_screenFieldCarpet_sausageIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_sausageIconDisabled';
		public static const fields_carpet_object_carpet_dove:String = 'fields/carpet/object_carpet/dove';
		public static const fields_carpet_object_carpet_parrot:String = 'fields/carpet/object_carpet/parrot';
		public static const fields_carpet_object_carpet_screenFieldCarpet_ball:String = 'fields/carpet/object_carpet/screenFieldCarpet_ball';
		public static const fields_carpet_object_carpet_screenFieldCarpet_canned:String = 'fields/carpet/object_carpet/screenFieldCarpet_canned';
		public static const fields_carpet_object_carpet_screenFieldCarpet_cookie:String = 'fields/carpet/object_carpet/screenFieldCarpet_cookie';
		public static const fields_carpet_object_carpet_screenFieldCarpet_mouse:String = 'fields/carpet/object_carpet/screenFieldCarpet_mouse';
		public static const fields_carpet_object_carpet_screenFieldCarpet_yorkshire:String = 'fields/carpet/object_carpet/screenFieldCarpet_yorkshire';
		public static const fields_window_component_screenFieldCWindow_furIcon:String = 'fields/window/component/screenFieldCWindow_furIcon';
		public static const fields_window_component_screenFieldCWindow_furIconDisabled:String = 'fields/window/component/screenFieldCWindow_furIconDisabled';
		public static const fields_window_component_screenFieldCWindow_hayIcon:String = 'fields/window/component/screenFieldCWindow_hayIcon';
		public static const fields_window_component_screenFieldCWindow_hayIconDisabled:String = 'fields/window/component/screenFieldCWindow_hayIconDisabled';
		public static const fields_window_component_screenFieldCWindow_paintblueIcon:String = 'fields/window/component/screenFieldCWindow_paintblueIcon';
		public static const fields_window_component_screenFieldCWindow_paintblueIconDisabled:String = 'fields/window/component/screenFieldCWindow_paintblueIconDisabled';
		public static const fields_window_component_screenFieldCWindow_paintredIconDisabled:String = 'fields/window/component/screenFieldCWindow_paintredIconDisabled';
		public static const fields_window_component_screenFieldCWindow_paintwhiteIcon:String = 'fields/window/component/screenFieldCWindow_paintwhiteIcon';
		public static const fields_window_component_screenFieldCWindow_paintwhiteIconDisabled:String = 'fields/window/component/screenFieldCWindow_paintwhiteIconDisabled';
		public static const fields_window_component_screenFieldCWindow_ragsIconDisabled:String = 'fields/window/component/screenFieldCWindow_ragsIconDisabled';
		public static const fields_window_component_screenFieldCWindow_woolIcon:String = 'fields/window/component/screenFieldCWindow_woolIcon';
		public static const fields_window_component_screenFieldCWindow_woolIconDisabled:String = 'fields/window/component/screenFieldCWindow_woolIconDisabled';
		public static const fields_window_object_window_camomile:String = 'fields/window/object_window/camomile';
		public static const fields_window_object_window_dog:String = 'fields/window/object_window/dog';
		public static const fields_window_object_window_rose:String = 'fields/window/object_window/rose';
		public static const fields_window_object_window_sheep:String = 'fields/window/object_window/sheep';
		public static const fields_window_object_window_violet:String = 'fields/window/object_window/violet';
		public static const header_band_experience_background:String = 'header/band_experience_background';
		public static const header_band_experience_stroke:String = 'header/band_experience_stroke';
		public static const header_header_counter_background:String = 'header/header_counter_background';
		public static const header_header_icon_ava:String = 'header/header_icon_ava';
		public static const header_header_icon_lexp:String = 'header/header_icon_lexp';
		public static const inventory_grey_icon_balls_shadow:String = 'inventory/grey_icon/balls_shadow';
		public static const inventory_grey_icon_box_shadow:String = 'inventory/grey_icon/box_shadow';
		public static const inventory_grey_icon_cookies_shadow:String = 'inventory/grey_icon/cookies_shadow';
		public static const inventory_grey_icon_feather_shadow:String = 'inventory/grey_icon/feather_shadow';
		public static const inventory_grey_icon_hay_shadow:String = 'inventory/grey_icon/hay_shadow';
		public static const inventory_grey_icon_mouse_shadow:String = 'inventory/grey_icon/mouse_shadow';
		public static const inventory_grey_icon_rabbit_fur_shadow:String = 'inventory/grey_icon/rabbit_fur_shadow';
		public static const inventory_grey_icon_rag_shadow:String = 'inventory/grey_icon/rag_shadow';
		public static const inventory_grey_icon_socks_shadow:String = 'inventory/grey_icon/socks_shadow';
		public static const inventory_grey_icon_spitsbl_shadow:String = 'inventory/grey_icon/spitsbl_shadow';
		public static const inventory_grey_icon_tangled_shadow:String = 'inventory/grey_icon/tangled_shadow';
		public static const inventory_grey_icon_toys_shadow:String = 'inventory/grey_icon/toys_shadow';
		public static const inventory_grey_icon_wool_shadow:String = 'inventory/grey_icon/wool_shadow';
		public static const inventory_grey_icon_wrappers_shadow:String = 'inventory/grey_icon/wrappers_shadow';
		public static const panel_tools_info_icon:String = 'panel_tools/info_icon';
		public static const panel_tools_info_icon_on:String = 'panel_tools/info_icon_on';
		public static const panel_tools_katyshka:String = 'panel_tools/katyshka';
		public static const panel_tools_korobka:String = 'panel_tools/korobka';
		public static const panel_tools_venik:String = 'panel_tools/venik';
		public static const start_windows_bg:String = 'start_windows/bg';
		public static const start_windows_button_buy:String = 'start_windows/button_buy';
		public static const start_windows_button_buy_on:String = 'start_windows/button_buy_on';
		public static const start_windows_tangled_icon:String = 'start_windows/tangled_icon';
		public static const fields_balls_component_screenFieldBalls_ballsIcon:String = 'fields/balls/component/screenFieldBalls_ballsIcon';
		public static const fields_balls_component_screenFieldBalls_sweaterIconDisabled:String = 'fields/balls/component/screenFieldBalls_sweaterIconDisabled';
		public static const fields_balls_object_balls_screenFieldBalls_ballGreen:String = 'fields/balls/object_balls/screenFieldBalls_ballGreen';
		public static const fields_balls_object_balls_screenFieldBalls_ballPurple:String = 'fields/balls/object_balls/screenFieldBalls_ballPurple';
		public static const fields_balls_object_balls_screenFieldBalls_ballWhite:String = 'fields/balls/object_balls/screenFieldBalls_ballWhite';
		public static const fields_balls_object_balls_screenFieldBalls_sweaterGreen:String = 'fields/balls/object_balls/screenFieldBalls_sweaterGreen';
		public static const fields_balls_object_balls_screenFieldBalls_toyBlue:String = 'fields/balls/object_balls/screenFieldBalls_toyBlue';
		public static const fields_balls_object_balls_screenFieldBalls_toyRed:String = 'fields/balls/object_balls/screenFieldBalls_toyRed';
		public static const fields_carpet_components_screenFieldCarpet_ballIcon:String = 'fields/carpet/components/screenFieldCarpet_ballIcon';
		public static const fields_carpet_components_screenFieldCarpet_ballIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_ballIconDisabled';
		public static const fields_carpet_components_screenFieldCarpet_cookieIcon:String = 'fields/carpet/components/screenFieldCarpet_cookieIcon';
		public static const fields_carpet_components_screenFieldCarpet_cookieIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_cookieIconDisabled';
		public static const fields_carpet_components_screenFieldCarpet_doveIcon:String = 'fields/carpet/components/screenFieldCarpet_doveIcon';
		public static const fields_carpet_components_screenFieldCarpet_doveIcon_Disabled:String = 'fields/carpet/components/screenFieldCarpet_doveIcon_Disabled';
		public static const fields_carpet_components_screenFieldCarpet_mouseIcon:String = 'fields/carpet/components/screenFieldCarpet_mouseIcon';
		public static const fields_carpet_components_screenFieldCarpet_mouseIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_mouseIconDisabled';
		public static const fields_carpet_components_screenFieldCarpet_threadIcon:String = 'fields/carpet/components/screenFieldCarpet_threadIcon';
		public static const fields_carpet_components_screenFieldCarpet_threadIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_threadIconDisabled';
		public static const fields_carpet_components_screenFieldCarpet_wrapperIcon:String = 'fields/carpet/components/screenFieldCarpet_wrapperIcon';
		public static const fields_carpet_components_screenFieldCarpet_wrapperIconDisabled:String = 'fields/carpet/components/screenFieldCarpet_wrapperIconDisabled';
		public static const fields_carpet_object_carpet_sausage:String = 'fields/carpet/object_carpet/sausage';
		public static const fields_carpet_object_carpet_screenFieldCarpet_goldfish:String = 'fields/carpet/object_carpet/screenFieldCarpet_goldfish';
		public static const fields_carpet_object_carpet_threads:String = 'fields/carpet/object_carpet/threads';
		public static const fields_carpet_object_carpet_wrapper:String = 'fields/carpet/object_carpet/wrapper';
		public static const fields_window_component_screenFieldCWindow_feathersIcon:String = 'fields/window/component/screenFieldCWindow_feathersIcon';
		public static const fields_window_component_screenFieldCWindow_feathersIconDisabled:String = 'fields/window/component/screenFieldCWindow_feathersIconDisabled';
		public static const fields_window_object_window_chiken:String = 'fields/window/object_window/chiken';
		public static const fields_window_object_window_grass:String = 'fields/window/object_window/grass';
		public static const fields_window_object_window_rag:String = 'fields/window/object_window/rag';
		public static const fields_window_object_window_shmel:String = 'fields/window/object_window/shmel';
		public static const inventory_grey_icon_dove_shadow:String = 'inventory/grey_icon/dove_shadow';
		public static const inventory_grey_icon_kolbasa_shadow:String = 'inventory/grey_icon/kolbasa_shadow';
		public static const inventory_grey_icon_nitki_shadow:String = 'inventory/grey_icon/nitki_shadow';
		public static const inventory_grey_icon_sweaters_shadow:String = 'inventory/grey_icon/sweaters_shadow';








		public static const font_large_white_bold:String = 'large_white_bold';


		public static const font_large_white_greenstroke_bold:String = 'large_white_greenstroke_bold';


		public static const font_medium_green_bold:String = 'medium_green_bold';


		public static const font_medium_white_bold:String = 'medium_white_bold';


		public static const font_small_brown_bold:String = 'small_brown_bold';


		public static const font_small_brown_regular:String = 'small_brown_regular';


		public static const font_small_milk_bold:String = 'small_milk_bold';


		public static const font_small_milk_regular:String = 'small_milk_regular';


		public static const font_small_white_greenstroke_bold:String = 'small_white_greenstroke_bold';


		public static const font_xlarge_milk_bold:String = 'xlarge_milk_bold';


		public static const font_xlarge_white_orangestroke_bold:String = 'xlarge_white_orangestroke_bold';


		public static const font_xsmall_brown_regular:String = 'xsmall_brown_regular';


		public static const font_xsmall_green_bold:String = 'xsmall_green_bold';


		public static const font_xsmall_grey_bold:String = 'xsmall_grey_bold';


		public static const font_xsmall_lightbrown_bold:String = 'xsmall_lightbrown_bold';


		public static const font_xsmall_milk_bold:String = 'xsmall_milk_bold';


		public static const font_xsmall_red_bold:String = 'xsmall_red_bold';

	}
}
